server:
  port: 8080
spring:
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.2.200:3306/aicv_web
    username: root
    password: root
  redis:
    database: 0
    host: 192.168.2.200
    port: 6379
  web:
    resources:
      add-mappings: false
  mvc:
    throw-exception-if-no-handler-found: true

  kafka:
    bootstrap-servers: 192.168.2.200:9092
    producer: # producer 生产者
      retries: 0 # 重试次数
      acks: 1 # 应答级别:多少个分区副本备份完成时向生产者发送ack确认(可选0、1、all/-1)
      batch-size: 16384 # 批量大小
      buffer-memory: 33554432 # 生产端缓冲区大小
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer: # consumer消费者
      group-id: mentugroup # 默认的消费组ID
      enable-auto-commit: true # 是否自动提交offset
      auto-commit-interval: 100  # 提交offset延时(接收到消息后多久提交offset)
      # earliest:当各分区下有已提交的offset时，从提交的offset开始消费；无提交的offset时，从头开始消费
      # latest:当各分区下有已提交的offset时，从提交的offset开始消费；无提交的offset时，消费新产生的该分区下的数据
      # none:topic各分区都存在已提交的offset时，从offset后开始消费；只要有一个分区不存在已提交的offset，则抛出异常
      auto-offset-reset: latest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

logging:
  level:
    com.jiangyun.aicvweb: DEBUG
    org.springframework: warn
    
mybatis:
  mapper-locations:
  - classpath:/mapper/*.xml
  
minio:
  url: http://192.168.2.200:9001
  username: jiangyun
  password: jiangyun
  
api:
  host: localhost:8080
  
wechat:
  officialAccount:
    appid: wx36966d016760cab8
    appsecret: 9ff7bf1680986917a9ea6427c6b6d996
    
tencentCloud:
  secretId: AKIDqWw5yauxkGLBk22lDPKyLSHp66pHSN1N
  secretKey: 6vTkjRs31i7G8k5B0Yprc6JEt31jCQTI
  sms:
    appId: 1400632359
    signName: 匠韵智能
    template:
      login: 1301336
  cos:
    bucketName: 1204-1309389332
    host: https://1204-1309389332.cos.ap-guangzhou.myqcloud.com
    region: ap-guangzhou
    